### ISSUE TITLE
urdf2graspit Segmentation fault

### ISSUE THREAD

**Issue by ilaplace** [JenniferBuehler/graspit-pkgs#19]
Hi there!

I was trying to convert my Allegro Hand to graspit but i can''t seem to succeed. I'm on ubuntu 14.04 and ros indigo. My command was:
`rosrun urdf2graspit urdf2graspit_node ~/catkin_ws/src/allegro-hand-ros/allegro_hand_description/allegro_hand_description_right.urdf  ~/catkin_ws/src/allegro-grasp hand_root joint_0.0 joint_12.0 joint_4.0 joint_8.0
`
And the output I got is:
semih@semih-ABRA-A5-V5-2:~/catkin_ws$ rosrun urdf2graspit urdf2graspit_node ~/catkin_ws/src/allegro-hand-ros/allegro_hand_description/allegro_hand_description_right.urdf  ~/catkin_ws/src/allegro-grasp hand_root joint_0.0 joint_12.0 joint_4.0 joint_8.0
[ INFO] [1487865360.317826574]: URDF file: /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/allegro_hand_description_right.urdf
[ INFO] [1487865360.317880353]: Output dir: /home/semih/catkin_ws/src/allegro-grasp
[ INFO] [1487865360.317902483]: Hand root: hand_root
[ INFO] [1487865360.317920406]: Joint: joint_0.0
[ INFO] [1487865360.317932440]: Joint: joint_12.0
[ INFO] [1487865360.317944300]: Joint: joint_4.0
[ INFO] [1487865360.317955251]: Joint: joint_8.0
[ INFO] [1487865360.318326704]: output_material: <plastic>
[ INFO] [1487865360.318723775]: scale_factor: <1000.000000>
[ INFO] [1487865360.319104789]: negate_joint_movement: <0>
[ INFO] [1487865360.320463164]: Starting model conversion...
[ INFO] [1487865360.320518059]: ### Loading from URDF file /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/allegro_hand_description_right.urdf...
[ INFO] [1487865360.320827677]: Setting base model directory to /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description
[ INFO] [1487865360.322679489]: ### Converting files starting from link hand_root
[ INFO] [1487865360.322702876]: ### Preparing for DH conversion...
[ INFO] [1487865360.322715922]: ### Joining fixed links..
[ INFO] [1487865360.322734181]: ############### Joining fixed links
[ INFO] [1487865360.322750204]: Start from root link: hand_root
[ INFO] [1487865360.322819400]: ### Transforming rotation axes to z...
[ INFO] [1487865360.322842287]: ############### Aligning rotation axis to [0, 0, 1]
[ INFO] [1487865360.322886480]: ### Converting files...
[ INFO] [1487865360.322903203]: ### Urdf2GraspIt::pretConvert for robot allegro_hand_right
[ INFO] [1487865360.322927195]: ##### Computing DH parameters out of model
[ INFO] [1487865360.322940396]: ############### Getting DH params
[ INFO] [1487865360.322953043]: ### Starting DH conversion from link hand_root
[ INFO] [1487865360.322966944]: ======== Transforming joint joint_0.0 to DH parameters
[ INFO] [1487865360.322980593]: ======== Transforming joint joint_1.0 to DH parameters
[ INFO] [1487865360.323011264]: z-axises intersect! [0, 0, 1] at [0, 0, 0], [0, -1, 2.22045e-16] at [0, 0, 0.0164]
[ INFO] [1487865360.323042400]: ======== Transforming joint joint_2.0 to DH parameters
[ INFO] [1487865360.323059025]: ======== Transforming joint joint_3.0 to DH parameters
[ INFO] [1487865360.323074338]: ======== Transforming joint joint_12.0 to DH parameters
[ INFO] [1487865360.323087350]: ======== Transforming joint joint_13.0 to DH parameters
[ INFO] [1487865360.323107295]: DEBUG-INFO DHParams: Correcting alpha: [-1, 0, 2.22045e-16], [1, 0, 2.83277e-16]
[ INFO] [1487865360.323123062]: ======== Transforming joint joint_14.0 to DH parameters
[ INFO] [1487865360.323145960]: z-axises intersect! [-1, 0, 2.22045e-16] at [-0.0399, 0.005, -0.027], [-2.22045e-16, -1, 4.93038e-32] at [-0.0576, 0.005, -0.027]
[ INFO] [1487865360.323166839]: DEBUG-INFO DHParams: Correcting theta: [2.22045e-16, 0, 1], [-2.22045e-16, 6.12323e-17, -1]
[ INFO] [1487865360.323181009]: ======== Transforming joint joint_15.0 to DH parameters
[ INFO] [1487865360.323196267]: ======== Transforming joint joint_4.0 to DH parameters
[ INFO] [1487865360.323209432]: ======== Transforming joint joint_5.0 to DH parameters
[ INFO] [1487865360.323228914]: z-axises intersect! [0, 0, 1] at [0, 0, 0], [0, -1, 2.22045e-16] at [0, 0, 0.0164]
[ INFO] [1487865360.323277083]: ======== Transforming joint joint_6.0 to DH parameters
[ INFO] [1487865360.323293661]: ======== Transforming joint joint_7.0 to DH parameters
[ INFO] [1487865360.323308853]: ======== Transforming joint joint_8.0 to DH parameters
[ INFO] [1487865360.323322586]: ======== Transforming joint joint_9.0 to DH parameters
[ INFO] [1487865360.323342593]: z-axises intersect! [0, 0, 1] at [0, 0, 0], [0, -1, 2.22045e-16] at [0, 0, 0.0164]
[ INFO] [1487865360.323357189]: ======== Transforming joint joint_10.0 to DH parameters
[ INFO] [1487865360.323372278]: ======== Transforming joint joint_11.0 to DH parameters
[ INFO] [1487865360.323389641]: ############### Transform links to DH reference frames
[ INFO] [1487865360.323444612]: --- DH Parameters: ---
[ INFO] [1487865360.323463702]: joint_0.0: d=0.0164, r=0, theta=0, alpha=1.5708, dof_idx=0
[ INFO] [1487865360.323479294]: joint_1.0: d=0, r=0.054, theta=1.5708, alpha=0, dof_idx=1
[ INFO] [1487865360.323493983]: joint_2.0: d=0, r=0.0384, theta=0, alpha=0, dof_idx=2
[ INFO] [1487865360.323508520]: joint_3.0: d=0, r=0, theta=0, alpha=0, dof_idx=3
[ INFO] [1487865360.323523287]: joint_12.0: d=0.027, r=0.005, theta=1.5708, alpha=-1.5708, dof_idx=4
[ INFO] [1487865360.323537945]: joint_13.0: d=0.0177, r=0, theta=-1.5708, alpha=1.5708, dof_idx=5
[ INFO] [1487865360.323552432]: joint_14.0: d=0, r=0.0514, theta=1.5708, alpha=0, dof_idx=6
[ INFO] [1487865360.323566973]: joint_15.0: d=0, r=0, theta=0, alpha=0, dof_idx=7
[ INFO] [1487865360.323581288]: joint_4.0: d=0.0164, r=0, theta=0, alpha=1.5708, dof_idx=8
[ INFO] [1487865360.323595918]: joint_5.0: d=0, r=0.054, theta=1.5708, alpha=0, dof_idx=9
[ INFO] [1487865360.323610363]: joint_6.0: d=0, r=0.0384, theta=0, alpha=0, dof_idx=10
[ INFO] [1487865360.323624418]: joint_7.0: d=0, r=0, theta=0, alpha=0, dof_idx=11
[ INFO] [1487865360.323638713]: joint_8.0: d=0.0164, r=0, theta=0, alpha=1.5708, dof_idx=12
[ INFO] [1487865360.323653109]: joint_9.0: d=0, r=0.054, theta=1.5708, alpha=0, dof_idx=13
[ INFO] [1487865360.323667680]: joint_10.0: d=0, r=0.0384, theta=0, alpha=0, dof_idx=14
[ INFO] [1487865360.323681879]: joint_11.0: d=0, r=0, theta=0, alpha=0, dof_idx=15
[ INFO] [1487865360.323693893]: ##### Scaling DH parameters
[ INFO] [1487865360.323707552]: ############### Scaling model
[ INFO] [1487865360.323765971]: ############### Converting meshes
[ INFO] [1487865360.323788126]: Convert mesh for link 'hand_root'
[ INFO] [1487865360.352503118]: Converting mesh file /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/meshes/base_link.STL with factor 1000
[ INFO] [1487865360.353169826]: Scaling the mesh /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/meshes/base_link.STL with factor 1000
[ INFO] [1487865360.381111647]: Convert mesh for link 'link_0.0'
[ INFO] [1487865360.422324023]: Converting mesh file /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_0.0.STL with factor 1000
[ INFO] [1487865360.422541524]: Scaling the mesh /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_0.0.STL with factor 1000
Coin warning in SoBase::setName(): Bad characters in name '_visual_0_link_0.0'. Replacing with name '_visual_0_link_0_0'
Coin warning in SoBase::setName(): Bad characters in name '_link_0.0'. Replacing with name '_link_0_0'
[ INFO] [1487865360.433109641]: Convert mesh for link 'link_1.0'
[ INFO] [1487865360.433186530]: Converting mesh file /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_1.0.STL with factor 1000
[ INFO] [1487865360.433368774]: Scaling the mesh /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_1.0.STL with factor 1000
Coin warning in SoBase::setName(): Bad characters in name '_visual_0_link_1.0'. Replacing with name '_visual_0_link_1_0'
Coin warning in SoBase::setName(): Bad characters in name '_link_1.0'. Replacing with name '_link_1_0'
[ INFO] [1487865360.445159858]: Convert mesh for link 'link_2.0'
[ INFO] [1487865360.445269595]: Converting mesh file /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_2.0.STL with factor 1000
[ INFO] [1487865360.445488119]: Scaling the mesh /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_2.0.STL with factor 1000
Coin warning in SoBase::setName(): Bad characters in name '_visual_0_link_2.0'. Replacing with name '_visual_0_link_2_0'
Coin warning in SoBase::setName(): Bad characters in name '_link_2.0'. Replacing with name '_link_2_0'
[ INFO] [1487865360.453968215]: Convert mesh for link 'link_3.0'
[ INFO] [1487865360.454034524]: Converting mesh file /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_3.0.STL with factor 1000
[ INFO] [1487865360.454135998]: Scaling the mesh /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_3.0.STL with factor 1000
Coin warning in SoBase::setName(): Bad characters in name '_visual_0_link_3.0'. Replacing with name '_visual_0_link_3_0'
[ INFO] [1487865360.454258345]: Converting mesh file /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_3.0_tip.STL with factor 1000
[ INFO] [1487865360.454458503]: Scaling the mesh /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_3.0_tip.STL with factor 1000
Coin warning in SoBase::setName(): Bad characters in name '_visual_1_link_3.0'. Replacing with name '_visual_1_link_3_0'
Coin warning in SoBase::setName(): Bad characters in name '_link_3.0'. Replacing with name '_link_3_0'
[ INFO] [1487865360.469439630]: Convert mesh for link 'link_12.0'
[ INFO] [1487865360.469574626]: Converting mesh file /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_12.0_right.STL with factor 1000
[ INFO] [1487865360.470240155]: Scaling the mesh /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_12.0_right.STL with factor 1000
Coin warning in SoBase::setName(): Bad characters in name '_visual_0_link_12.0'. Replacing with name '_visual_0_link_12_0'
Coin warning in SoBase::setName(): Bad characters in name '_link_12.0'. Replacing with name '_link_12_0'
[ INFO] [1487865360.506996159]: Convert mesh for link 'link_13.0'
[ INFO] [1487865360.507122141]: Converting mesh file /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_13.0.STL with factor 1000
[ INFO] [1487865360.507283615]: Scaling the mesh /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_13.0.STL with factor 1000
Coin warning in SoBase::setName(): Bad characters in name '_visual_0_link_13.0'. Replacing with name '_visual_0_link_13_0'
Coin warning in SoBase::setName(): Bad characters in name '_link_13.0'. Replacing with name '_link_13_0'
[ INFO] [1487865360.510889341]: Convert mesh for link 'link_14.0'
[ INFO] [1487865360.510949537]: Converting mesh file /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_14.0.STL with factor 1000
[ INFO] [1487865360.511092375]: Scaling the mesh /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_14.0.STL with factor 1000
Coin warning in SoBase::setName(): Bad characters in name '_visual_0_link_14.0'. Replacing with name '_visual_0_link_14_0'
Coin warning in SoBase::setName(): Bad characters in name '_link_14.0'. Replacing with name '_link_14_0'
[ INFO] [1487865360.518532106]: Convert mesh for link 'link_15.0'
[ INFO] [1487865360.518595875]: Converting mesh file /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_15.0.STL with factor 1000
[ INFO] [1487865360.518736116]: Scaling the mesh /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_15.0.STL with factor 1000
Coin warning in SoBase::setName(): Bad characters in name '_visual_0_link_15.0'. Replacing with name '_visual_0_link_15_0'
[ INFO] [1487865360.518874935]: Converting mesh file /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_15.0_tip.STL with factor 1000
[ INFO] [1487865360.519065277]: Scaling the mesh /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_15.0_tip.STL with factor 1000
Coin warning in SoBase::setName(): Bad characters in name '_visual_1_link_15.0'. Replacing with name '_visual_1_link_15_0'
Coin warning in SoBase::setName(): Bad characters in name '_link_15.0'. Replacing with name '_link_15_0'
[ INFO] [1487865360.538344687]: Convert mesh for link 'link_4.0'
[ INFO] [1487865360.538454084]: Converting mesh file /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_0.0.STL with factor 1000
[ INFO] [1487865360.538677071]: Scaling the mesh /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_0.0.STL with factor 1000
Coin warning in SoBase::setName(): Bad characters in name '_visual_0_link_4.0'. Replacing with name '_visual_0_link_4_0'
Coin warning in SoBase::setName(): Bad characters in name '_link_4.0'. Replacing with name '_link_4_0'
[ INFO] [1487865360.549032017]: Convert mesh for link 'link_5.0'
[ INFO] [1487865360.549104952]: Converting mesh file /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_1.0.STL with factor 1000
[ INFO] [1487865360.549292501]: Scaling the mesh /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_1.0.STL with factor 1000
Coin warning in SoBase::setName(): Bad characters in name '_visual_0_link_5.0'. Replacing with name '_visual_0_link_5_0'
Coin warning in SoBase::setName(): Bad characters in name '_link_5.0'. Replacing with name '_link_5_0'
[ INFO] [1487865360.560757470]: Convert mesh for link 'link_6.0'
[ INFO] [1487865360.560930394]: Converting mesh file /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_2.0.STL with factor 1000
[ INFO] [1487865360.561228623]: Scaling the mesh /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_2.0.STL with factor 1000
Coin warning in SoBase::setName(): Bad characters in name '_visual_0_link_6.0'. Replacing with name '_visual_0_link_6_0'
Coin warning in SoBase::setName(): Bad characters in name '_link_6.0'. Replacing with name '_link_6_0'
[ INFO] [1487865360.570184856]: Convert mesh for link 'link_7.0'
[ INFO] [1487865360.570271119]: Converting mesh file /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_3.0.STL with factor 1000
[ INFO] [1487865360.570406582]: Scaling the mesh /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_3.0.STL with factor 1000
Coin warning in SoBase::setName(): Bad characters in name '_visual_0_link_7.0'. Replacing with name '_visual_0_link_7_0'
[ INFO] [1487865360.570538719]: Converting mesh file /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_3.0_tip.STL with factor 1000
[ INFO] [1487865360.570723149]: Scaling the mesh /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_3.0_tip.STL with factor 1000
Coin warning in SoBase::setName(): Bad characters in name '_visual_1_link_7.0'. Replacing with name '_visual_1_link_7_0'
Coin warning in SoBase::setName(): Bad characters in name '_link_7.0'. Replacing with name '_link_7_0'
[ INFO] [1487865360.585580016]: Convert mesh for link 'link_8.0'
[ INFO] [1487865360.585648046]: Converting mesh file /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_0.0.STL with factor 1000
[ INFO] [1487865360.585825605]: Scaling the mesh /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_0.0.STL with factor 1000
Coin warning in SoBase::setName(): Bad characters in name '_visual_0_link_8.0'. Replacing with name '_visual_0_link_8_0'
Coin warning in SoBase::setName(): Bad characters in name '_link_8.0'. Replacing with name '_link_8_0'
[ INFO] [1487865360.596689663]: Convert mesh for link 'link_9.0'
[ INFO] [1487865360.596798463]: Converting mesh file /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_1.0.STL with factor 1000
[ INFO] [1487865360.597050495]: Scaling the mesh /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_1.0.STL with factor 1000
Coin warning in SoBase::setName(): Bad characters in name '_visual_0_link_9.0'. Replacing with name '_visual_0_link_9_0'
Coin warning in SoBase::setName(): Bad characters in name '_link_9.0'. Replacing with name '_link_9_0'
[ INFO] [1487865360.608345435]: Convert mesh for link 'link_10.0'
[ INFO] [1487865360.608415736]: Converting mesh file /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_2.0.STL with factor 1000
[ INFO] [1487865360.608580671]: Scaling the mesh /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_2.0.STL with factor 1000
Coin warning in SoBase::setName(): Bad characters in name '_visual_0_link_10.0'. Replacing with name '_visual_0_link_10_0'
Coin warning in SoBase::setName(): Bad characters in name '_link_10.0'. Replacing with name '_link_10_0'
[ INFO] [1487865360.616953647]: Convert mesh for link 'link_11.0'
[ INFO] [1487865360.617013129]: Converting mesh file /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_3.0.STL with factor 1000
[ INFO] [1487865360.617107700]: Scaling the mesh /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_3.0.STL with factor 1000
Coin warning in SoBase::setName(): Bad characters in name '_visual_0_link_11.0'. Replacing with name '_visual_0_link_11_0'
[ INFO] [1487865360.617228612]: Converting mesh file /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_3.0_tip.STL with factor 1000
[ INFO] [1487865360.617413579]: Scaling the mesh /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_3.0_tip.STL with factor 1000
Coin warning in SoBase::setName(): Bad characters in name '_visual_1_link_11.0'. Replacing with name '_visual_1_link_11_0'
Coin warning in SoBase::setName(): Bad characters in name '_link_11.0'. Replacing with name '_link_11_0'
[ INFO] [1487865360.635377698]: ### Urdf2GraspIt::postConvert for robot allegro_hand_right
Segmentation fault (core dumped)

**Comment by JenniferBuehler** [comment]
Hi,

sorry for having this trouble, and thanks for helping to test the converter with a new hand. I will look into this over the weekend. If you get around to it before then, it would help if you could send the output of a valgrind run:

```
sudo apt-get install valgrind (if you don't have it already)
cd <your catkin_ws>
catkin_make -DCMAKE_BUILD_TYPE=Debug
rosrun --prefix valgrind urdf2graspit urdf2graspit_node ~/catkin_ws/src/allegro-hand-ros/allegro_hand_description/allegro_hand_description_right.urdf ~/catkin_ws/src/allegro-grasp hand_root joint_0.0 joint_12.0 joint_4.0 joint_8.0
```

And also the link to the allegro URDF (git repo?) you are using would help me to test it.

Cheers
Jenny

**Comment by ilaplace** [comment]
Thanks for a quick response,

I'm working on a modified version of the xacro file over there:

[https://github.com/felixduvallet/allegro-hand-ros/tree/master/allegro_hand_description](url)

If you would like to see the exact one:

[https://drive.google.com/file/d/0B1AWehlT7E4xWVNPMXdQOGRscjA/view?usp=sharing](url)

And the output I got with your suggestion:

semih@semih-ABRA-A5-V5-2:~/graspit_ros_ws$ rosrun --prefix valgrind urdf2graspit urdf2graspit_node ~/catkin_ws/src/allegro-hand-ros/allegro_hand_description/allegro_hand_description_right.urdf ~/graspit_ros_ws/src/allegro-grasp hand_root joint_0.0 joint_12.0 joint_4.0 joint_8.0
==15312== Memcheck, a memory error detector
==15312== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==15312== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
==15312== Command: /home/semih/graspit_ros_ws/devel/lib/urdf2graspit/urdf2graspit_node /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/allegro_hand_description_right.urdf /home/semih/graspit_ros_ws/src/allegro-grasp hand_root joint_0.0 joint_12.0 joint_4.0 joint_8.0
==15312== 
[ INFO] [1487926150.532033539]: URDF file: /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/allegro_hand_description_right.urdf
[ INFO] [1487926150.555730079]: Output dir: /home/semih/graspit_ros_ws/src/allegro-grasp
[ INFO] [1487926150.570397681]: Hand root: hand_root
[ INFO] [1487926150.585749297]: Joint: joint_0.0
[ INFO] [1487926150.586800092]: Joint: joint_12.0
[ INFO] [1487926150.587703414]: Joint: joint_4.0
[ INFO] [1487926150.592983178]: Joint: joint_8.0
[ INFO] [1487926150.598172640]: output_material: <plastic>
[ INFO] [1487926150.634155235]: scale_factor: <1000.000000>
[ INFO] [1487926150.637387060]: negate_joint_movement: <0>
[ INFO] [1487926150.726192050]: Starting model conversion...
[ INFO] [1487926150.742835624]: ### Loading from URDF file /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description/allegro_hand_description_right.urdf...
[ INFO] [1487926150.778952318]: Setting base model directory to /home/semih/catkin_ws/src/allegro-hand-ros/allegro_hand_description
[ INFO] [1487926150.965064477]: ### Converting files starting from link hand_root
[ INFO] [1487926150.966526657]: ### Preparing for DH conversion...
[ INFO] [1487926150.967414703]: ### Joining fixed links..
[ INFO] [1487926150.968870644]: ############### Joining fixed links
[ INFO] [1487926150.970220518]: Start from root link: hand_root
[ INFO] [1487926151.377681329]: ### Transforming rotation axes to z...
[ INFO] [1487926151.386079466]: ############### Aligning rotation axis to [0, 0, 1]
[ INFO] [1487926151.562896971]: ### Converting files...
[ INFO] [1487926151.572490861]: ### Urdf2GraspIt::pretConvert for robot allegro_hand_right
[ INFO] [1487926151.587700689]: ##### Computing DH parameters out of model
[ INFO] [1487926151.588878658]: ############### Getting DH params
[ INFO] [1487926151.591863032]: ### Starting DH conversion from link hand_root
[ INFO] [1487926151.595827418]: ======== Transforming joint joint_0.0 to DH parameters
[ INFO] [1487926151.599571419]: ======== Transforming joint joint_1.0 to DH parameters
[ INFO] [1487926151.654010936]: z-axises intersect! [0, 0, 1] at [0, 0, 0], [0, -1, 2.22045e-16] at [0, 0, 0.0164]
[ INFO] [1487926151.681763903]: ======== Transforming joint joint_2.0 to DH parameters
[ INFO] [1487926151.693956879]: ======== Transforming joint joint_3.0 to DH parameters
[ INFO] [1487926151.698719016]: ======== Transforming joint joint_12.0 to DH parameters
[ INFO] [1487926151.699231042]: ======== Transforming joint joint_13.0 to DH parameters
[ INFO] [1487926151.704190207]: DEBUG-INFO DHParams: Correcting alpha: [-1, 0, 2.22045e-16], [1, 0, 2.83277e-16]
[ INFO] [1487926151.705399803]: ======== Transforming joint joint_14.0 to DH parameters
[ INFO] [1487926151.710583091]: z-axises intersect! [-1, 0, 2.22045e-16] at [-0.0399, 0.005, -0.027], [-2.22045e-16, -1, 4.93038e-32] at [-0.0576, 0.005, -0.027]
[ INFO] [1487926151.715311563]: DEBUG-INFO DHParams: Correcting theta: [2.22045e-16, 0, 1], [-2.22045e-16, 6.12323e-17, -1]
[ INFO] [1487926151.716964824]: ======== Transforming joint joint_15.0 to DH parameters
[ INFO] [1487926151.720839545]: ======== Transforming joint joint_4.0 to DH parameters
[ INFO] [1487926151.721362170]: ======== Transforming joint joint_5.0 to DH parameters
[ INFO] [1487926151.724412896]: z-axises intersect! [0, 0, 1] at [0, 0, 0], [0, -1, 2.22045e-16] at [0, 0, 0.0164]
[ INFO] [1487926151.725296210]: ======== Transforming joint joint_6.0 to DH parameters
[ INFO] [1487926151.728603533]: ======== Transforming joint joint_7.0 to DH parameters
[ INFO] [1487926151.731693637]: ======== Transforming joint joint_8.0 to DH parameters
[ INFO] [1487926151.732185517]: ======== Transforming joint joint_9.0 to DH parameters
[ INFO] [1487926151.735179928]: z-axises intersect! [0, 0, 1] at [0, 0, 0], [0, -1, 2.22045e-16] at [0, 0, 0.0164]
[ INFO] [1487926151.736036659]: ======== Transforming joint joint_10.0 to DH parameters
[ INFO] [1487926151.739307587]: ======== Transforming joint joint_11.0 to DH parameters
[ INFO] [1487926151.747809304]: ############### Transform links to DH reference frames
[ INFO] [1487926151.957089628]: --- DH Parameters: ---
[ INFO] [1487926151.960041159]: joint_0.0: d=0.0164, r=0, theta=0, alpha=1.5708, dof_idx=0
[ INFO] [1487926151.960601932]: joint_1.0: d=0, r=0.054, theta=1.5708, alpha=0, dof_idx=1
[ INFO] [1487926151.960995702]: joint_2.0: d=0, r=0.0384, theta=0, alpha=0, dof_idx=2
[ INFO] [1487926151.961391725]: joint_3.0: d=0, r=0, theta=0, alpha=0, dof_idx=3
[ INFO] [1487926151.961777600]: joint_12.0: d=0.027, r=0.005, theta=1.5708, alpha=-1.5708, dof_idx=4
[ INFO] [1487926151.962154758]: joint_13.0: d=0.0177, r=0, theta=-1.5708, alpha=1.5708, dof_idx=5
[ INFO] [1487926151.962532915]: joint_14.0: d=0, r=0.0514, theta=1.5708, alpha=0, dof_idx=6
[ INFO] [1487926151.962904638]: joint_15.0: d=0, r=0, theta=0, alpha=0, dof_idx=7
[ INFO] [1487926151.963279858]: joint_4.0: d=0.0164, r=0, theta=0, alpha=1.5708, dof_idx=8
[ INFO] [1487926151.963650412]: joint_5.0: d=0, r=0.054, theta=1.5708, alpha=0, dof_idx=9
[ INFO] [1487926151.964023584]: joint_6.0: d=0, r=0.0384, theta=0, alpha=0, dof_idx=10
[ INFO] [1487926151.964386303]: joint_7.0: d=0, r=0, theta=0, alpha=0, dof_idx=11
[ INFO] [1487926151.964769769]: joint_8.0: d=0.0164, r=0, theta=0, alpha=1.5708, dof_idx=12
[ INFO] [1487926151.965144397]: joint_9.0: d=0, r=0.054, theta=1.5708, alpha=0, dof_idx=13
[ INFO] [1487926151.965512343]: joint_10.0: d=0, r=0.0384, theta=0, alpha=0, dof_idx=14
[ INFO] [1487926151.965878775]: joint_11.0: d=0, r=0, theta=0, alpha=0, dof_idx=15
[ INFO] [1487926151.966792725]: ##### Scaling DH parameters
[ INFO] [1487926151.971851080]: ############### Scaling model
[ INFO] [1487926152.143541158]: ############### Converting meshes
[ INFO] [1487926152.150824620]: Convert mesh for link 'hand_root'
[ INFO] [1487926154.176972803]: Converting mesh file /home/semih/graspit_ros_ws/src/allegro-hand-ros/allegro_hand_description/meshes/base_link.STL with factor 1000
[ INFO] [1487926154.312969505]: Scaling the mesh /home/semih/graspit_ros_ws/src/allegro-hand-ros/allegro_hand_description/meshes/base_link.STL with factor 1000
[ INFO] [1487926156.074481963]: Convert mesh for link 'link_0.0'
[ INFO] [1487926157.245575949]: Converting mesh file /home/semih/graspit_ros_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_0.0.STL with factor 1000
[ INFO] [1487926157.287749935]: Scaling the mesh /home/semih/graspit_ros_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_0.0.STL with factor 1000
Coin warning in SoBase::setName(): Bad characters in name '_visual_0_link_0.0'. Replacing with name '_visual_0_link_0_0'
Coin warning in SoBase::setName(): Bad characters in name '_link_0.0'. Replacing with name '_link_0_0'
[ INFO] [1487926157.895884570]: Convert mesh for link 'link_1.0'
[ INFO] [1487926157.898570946]: Converting mesh file /home/semih/graspit_ros_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_1.0.STL with factor 1000
[ INFO] [1487926157.944996820]: Scaling the mesh /home/semih/graspit_ros_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_1.0.STL with factor 1000
Coin warning in SoBase::setName(): Bad characters in name '_visual_0_link_1.0'. Replacing with name '_visual_0_link_1_0'
Coin warning in SoBase::setName(): Bad characters in name '_link_1.0'. Replacing with name '_link_1_0'
[ INFO] [1487926158.586011458]: Convert mesh for link 'link_2.0'
[ INFO] [1487926158.588554784]: Converting mesh file /home/semih/graspit_ros_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_2.0.STL with factor 1000
[ INFO] [1487926158.645577052]: Scaling the mesh /home/semih/graspit_ros_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_2.0.STL with factor 1000
Coin warning in SoBase::setName(): Bad characters in name '_visual_0_link_2.0'. Replacing with name '_visual_0_link_2_0'
Coin warning in SoBase::setName(): Bad characters in name '_link_2.0'. Replacing with name '_link_2_0'
[ INFO] [1487926159.127240068]: Convert mesh for link 'link_3.0'
[ INFO] [1487926159.129800897]: Converting mesh file /home/semih/graspit_ros_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_3.0.STL with factor 1000
[ INFO] [1487926159.150060567]: Scaling the mesh /home/semih/graspit_ros_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_3.0.STL with factor 1000
Coin warning in SoBase::setName(): Bad characters in name '_visual_0_link_3.0'. Replacing with name '_visual_0_link_3_0'
[ INFO] [1487926159.155637082]: Converting mesh file /home/semih/graspit_ros_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_3.0_tip.STL with factor 1000
[ INFO] [1487926159.170034200]: Scaling the mesh /home/semih/graspit_ros_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_3.0_tip.STL with factor 1000
Coin warning in SoBase::setName(): Bad characters in name '_visual_1_link_3.0'. Replacing with name '_visual_1_link_3_0'
Coin warning in SoBase::setName(): Bad characters in name '_link_3.0'. Replacing with name '_link_3_0'
[ INFO] [1487926160.001216560]: Convert mesh for link 'link_12.0'
[ INFO] [1487926160.003750391]: Converting mesh file /home/semih/graspit_ros_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_12.0_right.STL with factor 1000
[ INFO] [1487926160.040596645]: Scaling the mesh /home/semih/graspit_ros_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_12.0_right.STL with factor 1000
Coin warning in SoBase::setName(): Bad characters in name '_visual_0_link_12.0'. Replacing with name '_visual_0_link_12_0'
Coin warning in SoBase::setName(): Bad characters in name '_link_12.0'. Replacing with name '_link_12_0'
[ INFO] [1487926162.038129724]: Convert mesh for link 'link_13.0'
[ INFO] [1487926162.040692072]: Converting mesh file /home/semih/graspit_ros_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_13.0.STL with factor 1000
[ INFO] [1487926162.050214175]: Scaling the mesh /home/semih/graspit_ros_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_13.0.STL with factor 1000
Coin warning in SoBase::setName(): Bad characters in name '_visual_0_link_13.0'. Replacing with name '_visual_0_link_13_0'
Coin warning in SoBase::setName(): Bad characters in name '_link_13.0'. Replacing with name '_link_13_0'
[ INFO] [1487926162.257258998]: Convert mesh for link 'link_14.0'
[ INFO] [1487926162.259820990]: Converting mesh file /home/semih/graspit_ros_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_14.0.STL with factor 1000
[ INFO] [1487926162.276277767]: Scaling the mesh /home/semih/graspit_ros_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_14.0.STL with factor 1000
Coin warning in SoBase::setName(): Bad characters in name '_visual_0_link_14.0'. Replacing with name '_visual_0_link_14_0'
Coin warning in SoBase::setName(): Bad characters in name '_link_14.0'. Replacing with name '_link_14_0'
[ INFO] [1487926162.701003963]: Convert mesh for link 'link_15.0'
[ INFO] [1487926162.703566151]: Converting mesh file /home/semih/graspit_ros_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_15.0.STL with factor 1000
[ INFO] [1487926162.720225191]: Scaling the mesh /home/semih/graspit_ros_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_15.0.STL with factor 1000
Coin warning in SoBase::setName(): Bad characters in name '_visual_0_link_15.0'. Replacing with name '_visual_0_link_15_0'
[ INFO] [1487926162.725475879]: Converting mesh file /home/semih/graspit_ros_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_15.0_tip.STL with factor 1000
[ INFO] [1487926162.736264725]: Scaling the mesh /home/semih/graspit_ros_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_15.0_tip.STL with factor 1000
Coin warning in SoBase::setName(): Bad characters in name '_visual_1_link_15.0'. Replacing with name '_visual_1_link_15_0'
Coin warning in SoBase::setName(): Bad characters in name '_link_15.0'. Replacing with name '_link_15_0'
[ INFO] [1487926163.790676133]: Convert mesh for link 'link_4.0'
[ INFO] [1487926163.794140749]: Converting mesh file /home/semih/graspit_ros_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_0.0.STL with factor 1000
[ INFO] [1487926163.798144185]: Scaling the mesh /home/semih/graspit_ros_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_0.0.STL with factor 1000
Coin warning in SoBase::setName(): Bad characters in name '_visual_0_link_4.0'. Replacing with name '_visual_0_link_4_0'
Coin warning in SoBase::setName(): Bad characters in name '_link_4.0'. Replacing with name '_link_4_0'
[ INFO] [1487926164.392669872]: Convert mesh for link 'link_5.0'
[ INFO] [1487926164.395378566]: Converting mesh file /home/semih/graspit_ros_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_1.0.STL with factor 1000
[ INFO] [1487926164.399402461]: Scaling the mesh /home/semih/graspit_ros_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_1.0.STL with factor 1000
Coin warning in SoBase::setName(): Bad characters in name '_visual_0_link_5.0'. Replacing with name '_visual_0_link_5_0'
Coin warning in SoBase::setName(): Bad characters in name '_link_5.0'. Replacing with name '_link_5_0'
[ INFO] [1487926165.031689403]: Convert mesh for link 'link_6.0'
[ INFO] [1487926165.034402656]: Converting mesh file /home/semih/graspit_ros_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_2.0.STL with factor 1000
[ INFO] [1487926165.037811667]: Scaling the mesh /home/semih/graspit_ros_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_2.0.STL with factor 1000
Coin warning in SoBase::setName(): Bad characters in name '_visual_0_link_6.0'. Replacing with name '_visual_0_link_6_0'
Coin warning in SoBase::setName(): Bad characters in name '_link_6.0'. Replacing with name '_link_6_0'
[ INFO] [1487926165.521412333]: Convert mesh for link 'link_7.0'
[ INFO] [1487926165.524154639]: Converting mesh file /home/semih/graspit_ros_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_3.0.STL with factor 1000
[ INFO] [1487926165.526063328]: Scaling the mesh /home/semih/graspit_ros_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_3.0.STL with factor 1000
Coin warning in SoBase::setName(): Bad characters in name '_visual_0_link_7.0'. Replacing with name '_visual_0_link_7_0'
[ INFO] [1487926165.530700954]: Converting mesh file /home/semih/graspit_ros_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_3.0_tip.STL with factor 1000
[ INFO] [1487926165.536017698]: Scaling the mesh /home/semih/graspit_ros_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_3.0_tip.STL with factor 1000
Coin warning in SoBase::setName(): Bad characters in name '_visual_1_link_7.0'. Replacing with name '_visual_1_link_7_0'
Coin warning in SoBase::setName(): Bad characters in name '_link_7.0'. Replacing with name '_link_7_0'
[ INFO] [1487926166.368390820]: Convert mesh for link 'link_8.0'
[ INFO] [1487926166.370959499]: Converting mesh file /home/semih/graspit_ros_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_0.0.STL with factor 1000
[ INFO] [1487926166.374532747]: Scaling the mesh /home/semih/graspit_ros_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_0.0.STL with factor 1000
Coin warning in SoBase::setName(): Bad characters in name '_visual_0_link_8.0'. Replacing with name '_visual_0_link_8_0'
Coin warning in SoBase::setName(): Bad characters in name '_link_8.0'. Replacing with name '_link_8_0'
[ INFO] [1487926166.970271904]: Convert mesh for link 'link_9.0'
[ INFO] [1487926166.972985227]: Converting mesh file /home/semih/graspit_ros_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_1.0.STL with factor 1000
[ INFO] [1487926166.976875765]: Scaling the mesh /home/semih/graspit_ros_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_1.0.STL with factor 1000
Coin warning in SoBase::setName(): Bad characters in name '_visual_0_link_9.0'. Replacing with name '_visual_0_link_9_0'
Coin warning in SoBase::setName(): Bad characters in name '_link_9.0'. Replacing with name '_link_9_0'
[ INFO] [1487926167.610848274]: Convert mesh for link 'link_10.0'
[ INFO] [1487926167.613499275]: Converting mesh file /home/semih/graspit_ros_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_2.0.STL with factor 1000
[ INFO] [1487926167.616631209]: Scaling the mesh /home/semih/graspit_ros_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_2.0.STL with factor 1000
Coin warning in SoBase::setName(): Bad characters in name '_visual_0_link_10.0'. Replacing with name '_visual_0_link_10_0'
Coin warning in SoBase::setName(): Bad characters in name '_link_10.0'. Replacing with name '_link_10_0'
[ INFO] [1487926168.096235591]: Convert mesh for link 'link_11.0'
[ INFO] [1487926168.098758334]: Converting mesh file /home/semih/graspit_ros_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_3.0.STL with factor 1000
[ INFO] [1487926168.100664415]: Scaling the mesh /home/semih/graspit_ros_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_3.0.STL with factor 1000
Coin warning in SoBase::setName(): Bad characters in name '_visual_0_link_11.0'. Replacing with name '_visual_0_link_11_0'
[ INFO] [1487926168.105002757]: Converting mesh file /home/semih/graspit_ros_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_3.0_tip.STL with factor 1000
[ INFO] [1487926168.108895632]: Scaling the mesh /home/semih/graspit_ros_ws/src/allegro-hand-ros/allegro_hand_description/meshes/link_3.0_tip.STL with factor 1000
Coin warning in SoBase::setName(): Bad characters in name '_visual_1_link_11.0'. Replacing with name '_visual_1_link_11_0'
Coin warning in SoBase::setName(): Bad characters in name '_link_11.0'. Replacing with name '_link_11_0'
[ INFO] [1487926168.957901808]: ### Urdf2GraspIt::postConvert for robot allegro_hand_right
urdf2graspit_node: /usr/include/boost/smart_ptr/shared_ptr.hpp:653: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = urdf::Inertial; typename boost::detail::sp_member_access<T>::type = urdf::Inertial*]: Assertion `px != 0' failed.
==15312== 
==15312== HEAP SUMMARY:
==15312==     in use at exit: 17,204,610 bytes in 71,415 blocks
==15312==   total heap usage: 430,052 allocs, 358,637 frees, 91,294,839 bytes allocated
==15312== 
==15312== LEAK SUMMARY:
==15312==    definitely lost: 8,936 bytes in 22 blocks
==15312==    indirectly lost: 6,720 bytes in 252 blocks
==15312==      possibly lost: 13,897,768 bytes in 64,590 blocks
==15312==    still reachable: 3,291,186 bytes in 6,551 blocks
==15312==         suppressed: 0 bytes in 0 blocks
==15312== Rerun with --leak-check=full to see details of leaked memory
==15312== 
==15312== For counts of detected and suppressed errors, rerun with: -v
==15312== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
Killed

**Comment by JenniferBuehler** [comment]
It was just something small in the end which was easy to find with gdb instead of valgrind :)
The hand doesn't have an inertial in the URDF, and I didn't catch that case in the converter, boh! I fixed it now.
Pull a new version of graspit-pkgs and it should work:

![image](https://cloud.githubusercontent.com/assets/12842634/23343912/7d855c62-fcc7-11e6-8688-c4261668b702.png)

**Comment by JenniferBuehler** [comment]
Let me know if it works for you now and if it does you can close the issue.

**Comment by ilaplace** [comment]
Yes I've created the file, but when I try to load world file it says: (If I make palm_link as wrist link)
```
Creating base...
Could not open /home/semih/catkin_ws/src/graspit-ros/graspit/graspit_source/models/robots/allegro_hand_right/iv/palm_link.xml
Failed to load base
Failed to load robot from file
Deleting Hand: 
Deleting grasp
Deleted robot: 
Could not open /home/semih/catkin_ws/src/graspit-ros/graspit/graspit_source/models/robots/allegro_hand_right/allegro_hand_right.xml
```

And if choose hand_root as the wrist link error becomes this:

```
Creating base...
invalid mass in dynamic body file: models/robots/allegro_hand_right/iv/hand_root.xml
Failed to load base
Failed to load robot from file
Deleting Hand: 
Deleting grasp
Deleted robot: 
Could not open /home/semih/catkin_ws/src/graspit-ros/graspit/graspit_source/models/robots/allegro_hand_right/allegro_hand_right.xml
```
And if I make the mass nonzero at hand_root.xml:

```xml
<?xml version="1.0" ?>
<root>
	<material>plastic</material>
	<mass>1</mass>
	<cog>0 0 0 </cog>
	<inertia_matrix>1 0 00 1 00 0 1</inertia_matrix>
	<geometryFile>hand_root.iv</geometryFile>
</root>
```

The new error:
```
Creating base...
Invalid Inertia Matrix Input
Failed to load base
Failed to load robot from file
Deleting Hand: 
Deleting grasp
Deleted robot: 
Could not open /home/semih/catkin_ws/src/graspit-ros/graspit/graspit_source/models/robots/allegro_hand_right/allegro_hand_right.xml

```

**Comment by ilaplace** [comment]
Actually after modifying the inertia_matrix like this:
```xml
	<inertia_matrix>1 0 0 0 1 0 0 0 1</inertia_matrix>
```
I can open the world file but it seems a bit weird though:

![image](https://cloud.githubusercontent.com/assets/16868900/23499391/61bd3a4c-ff45-11e6-8307-513f58b233d8.png)

**Comment by JenniferBuehler** [comment]
I am guessing that these are the problems you describe when opening the files in GraspIt?
The inertia seems to be important so it looks like GraspIt needs it. You may want to just add it in the URDF then it will be used by urdf2grapit to generate the files.

The output you are posting indeed looks like there is a problem with the DH parameters as well. I didn't try to open it in GraspIt.

I will try to make some time this weekend to look at this and let you know.

**Comment by JenniferBuehler** [comment]
Sorry, just saw the problem with the intertia matrix was because of the double 0s, my bad for not testing it in Graspit. I fixed it now so you should not have to manually edit the xml files any more.

As to the other problem with the thumb that is off, this is actually the same issue as #17. I'm looking into this, hopefully will be able to get back to you soon on this. Meanwhile you could try the in-between "fake link" as described in #17.

**Comment by JenniferBuehler** [comment]
I have made some sort of progress, though it's still not quite there... there's still some problems with the thumb. The first link's visual element is a bit off, and the rotation axes go the wrong way, which you will notice when you go to "Grasp -> EigenGrasp Interface" and handle the slider. This is an issue which I'm looking at now.

![image](https://cloud.githubusercontent.com/assets/12842634/23602301/06bab856-02a4-11e7-9224-6502c463f719.png)

Also note that the movement with the EigenGrasp Interface, and also the default position of the hand, is not really what it should be. This is because the automatically generated Eigen values are not particularly useful... this is something the user is expected to do manually (see also description [here](https://github.com/JenniferBuehler/graspit-pkgs/wiki/urdf2graspit#eigengrasp-notes) which refers to the file eigen/eigen.xml).

I have other problems with the allegro hand using the version of [simlab robotics](https://github.com/simlabrobotics/allegro_hand_ros) so I think this hand has exposed a few issues with urdf2graspit. I am working on it and will post updates here. Sorry this is not such a quick fix, I'm trying to allocate as much time as possible to fix this issue.

PS: As in the discussion of issue #17 it turns out the DH parameters *can* be calculated, this is what I fixed today. So you won't need the fake link, even if this may resolve the issue by coincidence and may be good to get a temporary fix.

**Comment by JenniferBuehler** [comment]
Btw you need to pull a new version of [urdf-tools-pkgs](https://github.com/JenniferBuehler/urdf-tools-pkgs) as well

**Comment by ilaplace** [comment]
Actually another interesting issue is that this is not the right hand :P. I have no idea why, I was just working with the right hand urdf but now it seems like I have a left hand.

**Comment by JenniferBuehler** [comment]
Indeed, you're right... I didn't notice that. The urdf may have been the wrong one. I just re-generated the right hand from the xacro and it looks ok:

![image](https://cloud.githubusercontent.com/assets/12842634/23629087/a9edb968-030a-11e7-8c56-50e8c11c4f2e.png)

I also fixed the directional issue with the grasping motion, so it now works with this model (except that the one link visual is still off). Still having troubles with the other repository's allegro hand, but that's something I won't get around to before next weekend.

Do a fresh pull of urdf-tools-pksg, graspit-pkgs and also re-generate your URDF and try again - hopefully you'll have something that you at least can work with this week.

**Comment by ilaplace** [comment]
I have generated the urdf from xacro like this: [https://github.com/felixduvallet/allegro-hand-ros](url) (from this fork)

`rosrun xacro xacro --inorder allegro_hand_description_right.xacro > allegro_hand_description_right.urdf`

And I still have the left hand: 
![image](https://cloud.githubusercontent.com/assets/16868900/23719894/6e689640-0456-11e7-8543-e073e51353b5.png)

May I ask which xacro did you use?
And despite that I updated my repositories it still look pretty bad. (I mean yours looks better)

**Comment by JenniferBuehler** [comment]
Oh weird, I'm pretty sure I was using the same repository. I'm at a different computer now but will check asap.
I forgot the ``--inorder``, otherwise I used the same command.

The output (weird thumb) also looks like you don't have the newest version of urdf-tools-pkgs, did you pull and re-build both urdf-tools-pkgs and graspit-pkgs? I had the same strange thumb before.

**Comment by ilaplace** [comment]
Sorry rookie mistake, I've forgotten to build again, mine looks like yours now

**Comment by JenniferBuehler** [comment]
I now finally got it to work with the hand in the original repository as well:

![image](https://cloud.githubusercontent.com/assets/12842634/23829169/14da4700-073e-11e7-97f4-37a3cbb0a89c.png)

It was a bug in urdf2graspit which remained undiscovered with the other hands - thanks for posting the issue so I could track it!

With the fork by felixduvallet I still have problem that the visual is a bit off. I'm not sure if it's a problem with the modified URDF (and maybe modified mesh files?), I haven't tracked it down. But even with my simple URDF viewer it also looks like that, which makes me think it may be an issue with the URDF itself (since it works with the original now):

![image](https://cloud.githubusercontent.com/assets/12842634/23829188/c9637822-073e-11e7-8218-5bf291063bcb.png)

Have you opened the hand with other URDF viewers, or Gazebo, and not observed the same problem with the thumb link? If so, please let me know and I'll see if this is another bug. 

You need to pull urdf-tools-pkgs and graspit-pkgs again.

**Comment by JenniferBuehler** [comment]
***PS:*** You can use a launch files like this, which makes life a bit easier (root link name as for the repository by felixduvallet, change it if you are going to use the original repo):

For the URDF viewer:
```xml
<launch>                                                                                            
    <arg name="urdf_file" default="$(find allegro_hand_description)/allegro_hand_description_right.urdf"/>
                                                                                                    
    <!-- command line parameter -->                                                                 
    <arg name="iv_or_link" default=""/>                                                             
                                                                                                    
    <arg name="join_fixed_links" default="false"/>                                                  
    <arg name="rotate_axes_z" default="false"/>                                                     
    <arg name="display_axes" default="true"/>                                                       
    <arg name="axes_radius" default="0.001"/>                                                       
    <arg name="axes_length" default="0.015"/>                                                       
                                                                                                    
    # An axis and angle (degrees) can be specified which will transform *all*                       
    # visuals (not links, but their visuals!) within their local coordinate system.                 
    # This can be used to correct transformation errors which may have been                         
    # introduced in converting meshes from one format to the other, losing orientation information  
    # For example, .dae has an "up vector" definition which may have been ignored.                  
    <arg name="visual_corr_axis_x" default="1"/>                                                    
    <arg name="visual_corr_axis_y" default="0"/>                                                    
    <arg name="visual_corr_axis_z" default="0"/>                                                    
    <arg name="visual_corr_axis_angle" default="0"/>                                                
                                                                                                    
  <node name="urdf_viewer" pkg="urdf_viewer" type="urdf_viewer_node" respawn="false"                
        output="screen" args="$(arg urdf_file) $(arg iv_or_link)">                                  
    <param name="join_fixed_links" value="$(arg join_fixed_links)"/>                                
    <param name="rotate_axes_z" value="$(arg rotate_axes_z)"/>                                      
    <param name="display_axes" value="$(arg display_axes)"/>                                        
    <param name="axes_radius" value="$(arg axes_radius)"/>                                          
    <param name="axes_length" value="$(arg axes_length)"/>                                          
    <param name="visual_corr_axis_x" value="$(arg visual_corr_axis_x)"/>                            
    <param name="visual_corr_axis_y" value="$(arg visual_corr_axis_y)"/>                            
    <param name="visual_corr_axis_z" value="$(arg visual_corr_axis_z)"/>                            
    <param name="visual_corr_axis_angle" value="$(arg visual_corr_axis_angle)"/>                    
  </node>                                                                                           
</launch>     
```

For the urdf2graspit converter:

```xml
<launch>                                                                                            
  # the input urdf file                                                                             
  <arg name="urdf_file" default="$(find allegro_hand_description)/allegro_hand_description_right.urdf"/>
                                                                                                    
  # the directory onto which to write the output files                                              
  <arg name="output_directory"/>                                                                    
  <arg name="hand_root_link" default="palm_link"/>                                                  
  <arg name="finger_joint_names" default="joint_0.0 joint_12.0 joint_4.0 joint_8.0"/>               
  <arg name="scale_factor" default="1000"/>                                                         
                                                                                                    
  <arg name="output_material" default="plastic"/>                                                   
                                                                                                    
  <arg name="launch_prefix" default=""/>                                                            
                                                                                                    
  <include file="$(find urdf2graspit)/launch/urdf2graspit.launch">                                  
    <arg name="launch_prefix" value="$(arg launch_prefix)"/>                                        
    <arg name="urdf_file" value="$(arg urdf_file)"/>                                                
    <arg name="output_directory" value="$(arg output_directory)"/>                                  
    <arg name="hand_root_link" value="$(arg hand_root_link)"/>                                      
    <arg name="finger_joint_names" value="$(arg finger_joint_names)"/>                              
    <arg name="scale_factor" value="$(arg scale_factor)"/>                                          
    <arg name="output_material" value="$(arg output_material)"/>                                    
    <arg name="negate_joint_movement" value="false"/>                                               
  </include>                                                                                        
</launch>    
```

And for the contacts editor:

```xml
<launch>                                                                                            
    # the input urdf file                                                                           
    <arg name="urdf_file" default="$(find allegro_hand_description)/allegro_hand_description_right.urdf"/>
                                                                                                    
    # the directory onto which to write the output files                                            
    <arg name="output_directory"/>                                                                  
                                                                                                    
    <arg name="hand_root_link" default="palm_link"/>                                                
    <arg name="finger_joint_names" default="joint_0.0 joint_12.0 joint_4.0 joint_8.0"/>             
                                                                                                    
    <arg name="scale_factor" default="1000"/>                                                       
                                                                                                    
    # if this is true, the DH axes are displayed. Otherwise, the URDF axes are displayed.           
    <arg name="display_dh_axes" default="true"/>                                                    
                                                                                                    
    <include file="$(find urdf2graspit)/launch/graspit_contacts_generator.launch">                  
        <arg name="urdf_file" value="$(arg urdf_file)"/>                                            
        <arg name="output_directory" value="$(arg output_directory)"/>                              
        <arg name="hand_root_link" value="$(arg hand_root_link)"/>                                  
        <arg name="finger_joint_names" value="$(arg finger_joint_names)"/>                          
        <arg name="scale_factor" value="$(arg scale_factor)"/>                                      
        <arg name="display_dh_axes" value="$(arg display_dh_axes)"/>                                
    <arg name="negate_joint_movement" value="false"/>                                               
    </include>                                                                                      
</launch>
```

**Comment by ilaplace** [comment]
Actually the original urdf file gives me the error:
```
[ INFO] [1489325562.415584363]: ############### Joining fixed links
[ INFO] [1489325562.415600085]: Start from root link: palm_link
[ERROR] [1489325562.415630760]: No link named 'palm_link'
[ERROR] [1489325562.415644672]: Could not join fixed links
[ERROR] [1489325562.415654185]: Could not prepare for DH conversion
[ERROR] [1489325562.415669295]: Failed to process.
```

Any idea what is this about?

**Comment by JenniferBuehler** [comment]
You have to change the link name, in the original it's not palm_link, I
think it was base_link

**Comment by JenniferBuehler** [comment]
Did you try again? Did it work? If it did, feel free to close the issue.

**Comment by ilaplace** [comment]
It worked, thank you for your help!
